# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: false
addons:
  apt:
    packages:
    - imagemagick
    - tcl8.5
    - tk8.5
    - libcairo2
    - libavcodec-extra-54
    - libavdevice53
    - libavfilter3
    - libavformat54
    - libavutil-extra-52
    - libswscale2
    - libgtk-3-dev
    - zlib1g-dev
os:
  - linux
#  - osx
julia:
  - 1.0
  - nightly
# matrix:	
#   allow_failures:
#     - julia: nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
# script:
#  - julia -e 'Pkg.clone(pwd())'
#  - julia -e 'Pkg.build("VideoIO")'
#  - if [ -f test/runtests.jl ]; then julia -e 'Pkg.test("VideoIO", coverage=true)'; fi
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("VideoIO")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("VideoIO")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
