environment:
  matrix:
  - julia_version: 1.0  
  - julia_version: 1.1
  - julia_version: latest

platform:
  - x86 # 32-bit
  - x64 # 64-bit

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia_version: latest

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

cache:
  - C:\Users\appveyor\.julia\packages\Homebrew
  - C:\Users\appveyor\.julia\packages\LibCURL
  - C:\Users\appveyor\.julia\packages\WinRPM
  - C:\Users\appveyor\.julia\packages\Cairo
  - C:\Users\appveyor\.julia\packages\Conda
  - C:\Users\appveyor\.julia\packages\FFTW
  - C:\Users\appveyor\.julia\packages\SpecialFunctions
  - C:\Users\appveyor\.julia\packages\Gtk
  - C:\Users\appveyor\.julia\packages\ImageMagick
    
install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
