name = "VideoIO"
uuid = "d6d074c3-1acf-5d4c-9a43-ef38773959a2"
version = "0.9.5"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
ColorTypes = "0.9, 0.10, 0.11"
Downloads = "1.3"
FFMPEG = "0.2, 0.3, 0.4"
FileIO = "1.6"
Glob = "1.2"
ImageCore = "0.8, 0.9"
ProgressMeter = "1.2"
Requires = "1.0"
julia = "1.3"
